### PR TITLE
[2.x] Updated Class Names to commonly using form

### PR DESCRIPTION
**Pull request by voyula**
Updated Class Names to commonly using form.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is a major breaking change because it breaks autoloading on case-sensitive filesystems..

**Comment by GrahamCampbell** [comment]
This PR doesn't do what it says btw. PSR-4 says nothing about having to use uppercase for the first name of the vendor. It actually says:

> Alphabetic characters in the fully qualified class name MAY be any combination of lower case and upper case.

**Comment by voyula** [comment]
@GrahamCampbell Commonly Studly Case using of php packages.

**Comment by GrahamCampbell** [comment]
But not required for PSR-4...

**Comment by voyula** [comment]
@GrahamCampbell Ok, updated.

**Pull request closed without merging**
