### PR TITLE
Support for PHPUnit 10

### PR DESCRIPTION
**Pull request by Braunson**
Support for PHPUnit 10

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This change is not enough. You'll need to upgrade the config.

**Comment by Braunson** [comment]
> This change is not enough. You'll need to upgrade the config.

The PHPUnit config? Can do.

**Comment by Braunson** [comment]
The tests seem to be failing due to non-code related issue?

```
In RepositoryIntrospector.php line 39:
                                                                               
  Failed to retrieve commit parents. If you use a shallow git checkout, pleas  
  e checkout at least a depth of one.                                          
                                                                               

code-coverage:upload [--api-url API-URL] [--repository REPOSITORY] [--revision REVISION] [--format FORMAT] [--parent PARENT] [--] <coverage-file>
```

**Comment by Braunson** [comment]
Is this package no longer being supported?

**Comment by GrahamCampbell** [comment]
I don't think it's a good idea to upgrade to PHPUnit 10 TBH, because they make breaking changes in every minor release. I'd hold off till PHPUnit 11 is out before upgrading.

**Pull request closed without merging**
